/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainWindow.java
 *
 * Created on 01/07/2010, 18:33:37
 */

package UI;

import java.util.LinkedList;
import java.util.List;

/**
 *
 * @author alverbner
 */
public class MainWindow extends javax.swing.JFrame {

    private List<Step> steps;
    private int activeStep;

    private void loadSteps(){
        this.activeStep = 0;
        this.steps = new LinkedList<Step>();
        steps.add(this.step_1);
        this.step_2.setVisible(false);
        steps.add(this.step_2);
        this.step_3.setVisible(false);
        steps.add(this.step_3);
        this.step_4.setVisible(false);
        steps.add(this.step_4);
        this.step_5.setVisible(false);
        steps.add(this.step_5);
        
        
    }

    /** Creates new form MainWindow */
    public MainWindow() {
        initComponents();
        loadSteps();
        getRootPane().setDefaultButton(this.nextButton);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nextButton = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        step_1 = new UI.Step1();
        step_2 = new UI.Step2();
        step_3 = new UI.Step3();
        step_4 = new UI.Step4();
        step_5 = new UI.Step5();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nextButton.setText("Seguir >>");
        nextButton.setName("nextButton"); // NOI18N
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        jLayeredPane1.setName("jLayeredPane1"); // NOI18N

        step_1.setName("step_1"); // NOI18N
        step_1.setBounds(0, 0, 580, 270);
        jLayeredPane1.add(step_1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        step_2.setName("step_2"); // NOI18N
        step_2.setBounds(3, 3, 580, 270);
        jLayeredPane1.add(step_2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        step_3.setName("step_3"); // NOI18N
        step_3.setBounds(0, 0, 580, 270);
        jLayeredPane1.add(step_3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        step_4.setName("step_4"); // NOI18N
        step_4.setBounds(0, 0, 442, 223);
        jLayeredPane1.add(step_4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        step_5.setName("step_5"); // NOI18N
        step_5.setBounds(10, 0, 495, 223);
        jLayeredPane1.add(step_5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        fileMenu.setText("Archivo");

        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nextButton)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        boolean mustReExecute = this.steps.get(this.activeStep).executeStep();
        if( mustReExecute )
            return;
        
        this.steps.get(this.activeStep).setVisible(false);

        this.activeStep ++;

        if( this.activeStep == this.steps.size() )
            this.activeStep = 0;

        while(! this.steps.get(this.activeStep).isActive())
            this.activeStep++;        
        
        this.steps.get(this.activeStep).setVisible(true);
    }//GEN-LAST:event_nextButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton nextButton;
    private UI.Step1 step_1;
    private UI.Step2 step_2;
    private UI.Step3 step_3;
    private UI.Step4 step_4;
    private UI.Step5 step_5;
    // End of variables declaration//GEN-END:variables

}
