/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Step1.java
 *
 * Created on 01/07/2010, 18:53:55
 */
package UI;

import java.awt.Dialog;
import javax.swing.JOptionPane;
import modelo.Game;

/**
 *
 * @author alverbner
 */
public class Step1 extends Step {

    /** Creates new form Step1 */
    public Step1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        playerCount = new javax.swing.JTextField();

        jLabel1.setText("Por favor, ingrese la cantidad de contrincantes:");
        jLabel1.setName("jLabel1"); // NOI18N

        playerCount.setName("playerCount"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(playerCount, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(playerCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(173, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField playerCount;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean executeStep() {
        this.setActive(false);

        try {
            int players = Integer.parseInt(this.playerCount.getText());
            Game.getInstance().createPlayers(players);
            return false;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ingrese un valor numérico", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return true;
        }
    }
}
