/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Step1.java
 *
 * Created on 01/07/2010, 18:53:55
 */
package UI;

import javax.swing.JOptionPane;
import modelo.Game;
import modelo.Jugador.Mano;
import java.awt.Color;

/**
 *
 * @author alverbner
 */
public class Step2 extends Step {

    /** Creates new form Step1 */
    public Step2() {
        initComponents();
        LoadManos();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel1.setForeground(Color.WHITE);
        montoMano = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setForeground(Color.WHITE);
        apuestaRequerida = new javax.swing.JTextField();
        manos = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setForeground(Color.WHITE);

        jLabel1.setText("Monto de la mano:");
        jLabel1.setName("jLabel1"); // NOI18N

        montoMano.setName("montoMano"); // NOI18N

        jLabel2.setText("Apuesta requerida:");
        jLabel2.setName("jLabel2"); // NOI18N
        
        this.setBackground("imagenes/snookar-cloth-first-grade.jpg");

        apuestaRequerida.setName("apuestaRequerida"); // NOI18N

        manos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        manos.setName("manos"); // NOI18N
        manos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manosActionPerformed(evt);
            }
        });

        jLabel3.setText("Mano:");
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(montoMano, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manos, 0, 129, Short.MAX_VALUE)
                            .addComponent(apuestaRequerida, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(montoMano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(apuestaRequerida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(manos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manosActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apuestaRequerida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox manos;
    private javax.swing.JTextField montoMano;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean executeStep() {
        try {
            int apuesta = Integer.parseInt(this.apuestaRequerida.getText());
            int monto = Integer.parseInt(this.montoMano.getText());
            Mano manoJugador = (Mano) this.manos.getSelectedItem();
            Game.getInstance().setApuesta(apuesta);
            Game.getInstance().setMonto(monto);
            Game.getInstance().getJugador().setMano(manoJugador);
            Game.getInstance().Run();
            return false;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ingrese un valor numérico", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return true;
        }
    }

    private void LoadManos() {
        this.manos.removeAllItems();
        for (final Mano mano : Mano.values()) {
            this.manos.addItem(mano);
        }
    }
}
