/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Step1.java
 *
 * Created on 01/07/2010, 18:53:55
 */
package UI;

import modelo.Contrincante;
import modelo.Game;
import modelo.Jugador;
import modelo.Jugador.Accion;
import modelo.Jugador.Mano;

/**
 *
 * @author alverbner
 */
public class Step4 extends Step {

    private int jugadorActual = 0;

    /** Creates new form Step1 */
    public Step4() {
        initComponents();
        LoadAcciones();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        acciones = new javax.swing.JComboBox();

        label.setText("Acción jugador 1:");
        label.setName("label"); // NOI18N

        acciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        acciones.setName("acciones"); // NOI18N
        acciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(label)
                .addGap(18, 18, 18)
                .addComponent(acciones, 0, 147, Short.MAX_VALUE)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label)
                    .addComponent(acciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(173, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void accionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accionesActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox acciones;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean executeStep() {
        
            
            Jugador.Accion accion = (Jugador.Accion) this.acciones.getSelectedItem();
            Contrincante contrincante = Game.getInstance().getJugador().getContrincantes().get(this.jugadorActual);
            switch (accion) {
                case Call:
                    contrincante.setCantidadCall(contrincante.getCantidadCall() + 1);
                    break;
                case Raise:
                    contrincante.setCantidadRaise(contrincante.getCantidadRaise() + 1);
                    break;
                case Fold:
                    contrincante.setCantidadFold(contrincante.getCantidadFold() + 1);
                    break;
            }
            this.jugadorActual++;
            this.label.setText("Accion jugador " + (this.jugadorActual + 1));
        return this.jugadorActual < Game.getInstance().getJugador().getContrincantes().size() ;
    }

    @Override
    public void setVisible(boolean visible) {
        this.label.setText("Accion jugador 1");
        this.jugadorActual = 0;
        super.setVisible(visible);
    }

    private void LoadAcciones() {
        this.acciones.removeAllItems();
        for (final Accion accion : Jugador.Accion.values()) {
            this.acciones.addItem(accion);
        }
    }
}
