/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Step1.java
 *
 * Created on 01/07/2010, 18:53:55
 */
package UI;

import modelo.Contrincante;
import modelo.Game;
import modelo.Jugador;
import modelo.Jugador.Accion;
import java.awt.Color;

public class Step5 extends Step {

    private int jugadorActual = 0;

    /** Creates new form Step1 */
    public Step5() {
        initComponents();
        LoadJugadores();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        label.setForeground(Color.WHITE);
        jugadores = new javax.swing.JComboBox();

        label.setText("El ganador de la partida fue:");
        label.setName("label"); // NOI18N

        jugadores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jugadores.setName("jugadores"); // NOI18N
        jugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugadoresActionPerformed(evt);
            }
        });
        
        this.setBackground("imagenes/snookar-cloth-first-grade.jpg");
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(label)
                .addGap(18, 18, 18)
                .addComponent(jugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label)
                    .addComponent(jugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(173, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jugadoresActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jugadores;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean executeStep() {
        int selectedIndex = this.jugadores.getSelectedIndex();
        if( selectedIndex > 0 ){
            Contrincante contrincante =  Game.getInstance().getJugador().getContrincantes().get(selectedIndex - 1);
            contrincante.setRondasGanadas(contrincante.getRondasGanadas() + 1);
          
        }
        return false;

    }

    @Override
    public void setVisible(boolean visible) {
        LoadJugadores();
        super.setVisible(visible);
    }

    private void LoadJugadores() {
        this.jugadores.removeAllItems();
        this.jugadores.addItem("Usted");
        for (int i = 0; i < Game.getInstance().getJugador().getContrincantes().size(); i++) {
            this.jugadores.addItem("Jugador " + (i + 1));
        }
    }
}
