/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Step1.java
 *
 * Created on 01/07/2010, 18:53:55
 */
package UI;

import java.awt.Dialog;
import java.awt.Graphics;
import java.awt.Image;

import javax.swing.JOptionPane;

import modelo.Game;

import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.ImageIcon;
import java.awt.Color;


public class Step1 extends Step {

    /** Creates new form Step1 */
    public Step1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel1.setForeground(Color.WHITE);
        playerCount = new javax.swing.JTextField();

        jLabel1.setText("Por favor, ingrese la cantidad de contrincantes:");
        jLabel1.setName("jLabel1"); // NOI18N

        playerCount.setName("playerCount");
        
        this.setBackground("imagenes/snookar-cloth-first-grade.jpg");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(34)
        			.addComponent(jLabel1)
        			.addGap(18)
        			.addComponent(playerCount, GroupLayout.PREFERRED_SIZE, 129, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(30)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1)
        				.addComponent(playerCount, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(251, Short.MAX_VALUE))
        );
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField playerCount;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean executeStep() {
        this.setActive(false);

        try {
            int players = Integer.parseInt(this.playerCount.getText());
            Game.getInstance().createPlayers(players);
            return false;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ingrese un valor numérico", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return true;
        }
    }
}
