(ns fallas)

(println "Cantidad de jugadores? (1 a 6)")
(def jugadores (read-line))

(println "Monto de la mesa?")
(def monto (read-line))

(println "Apuesta?")
(def apuesta (read-line))

(println "Ingrese numero de mano")
(println "1. Carta")
(println "2. Par")
(println "3. Par Doble")
(println "4. Trio")
(println "5. Escalera")
(println "6. Color")
(println "7. Full")
(println "8. Poker")
(println "9. Escalera Real")
(def mano (read-line))

(def montoApuesta (quot (read-string monto) (read-string apuesta))
)

(defn jugada [jugadores monto apuesta mano montoApuesta]
  (if (= mano "1")
    (println "Fold"))
  (if (= mano "2")
    (println "Fold"))
  (if (= mano "3")
    (if (>= montoApuesta 9)
    	(println "Call")
    	(println "Fold")
    )
  )
  (if (= mano "4")
    (if (>= montoApuesta 6)
    	(println "Call")
    	(println "Fold")
    )
  )
  (if (= mano "5")
    (if (>= montoApuesta 4)
    	(println "Call")
    	(println "Fold")
    )
  )
  (if (= mano "6")
    (if (>= montoApuesta 2)
    	(println "Raise")
    	(println "Call")
    )
  )
  (if (= mano "7")
    (println "Call"))
  (if (= mano "8")
    (println "Call"))
  (if (= mano "9")
    (println "Call")
  )
)

(jugada jugadores monto apuesta mano montoApuesta)
